### ISSUE TITLE
migrates validatejs  normal predicate methods

### ISSUE THREAD

**Issue by shizhipeng** [Qquanwei/OverAssert#3]
- [x] 1. required: 'The %s field is required.',
- [x] 2. matches: 'The %s field does not match the %s field.',
- [ ] 3. default: 'The %s field is still set to default, please change.',
- [ ] 4. valid_email: 'The %s field must contain a valid email address.',
- [ ] 5. valid_emails: 'The %s field must contain all valid email addresses.',
- [x] 8. exact_length: 'The %s field must be exactly %s characters in length.',
- [x] 6. min_length: 'The %s field must be at least %s characters in length.',
- [x] 7. max_length: 'The %s field must not exceed %s characters in length.',
- [x] 9. greater_than: 'The %s field must contain a number greater than %s.',
- [x] 10. less_than: 'The %s field must contain a number less than %s.',
- [x] 11. alpha: 'The %s field must only contain alphabetical characters.',
- [x] 14. numeric: 'The %s field must contain only numbers.',
- [x] 15. integer: 'The %s field must contain an integer.',
- [x] 16. decimal: 'The %s field must contain a decimal number.',
- [x] 17.  is_natural: 'The %s field must contain only positive numbers.',
- [x] 18. is_natural_no_zero: 'The %s field must contain a number greater than zero.',
- [x] 19. valid_ip: 'The %s field must contain a valid IP.',
- [x] 23. valid_url: 'The %s field must contain a valid URL.',
- [x] 13.  alpha_dash: 'The %s field must only contain alpha-numeric characters, underscores, and dashes.',
- [ ] 12.  alpha_numeric: 'The %s field must only contain alpha-numeric characters.',
- [ ] 20. valid_base64: 'The %s field must contain a base64 string.',
- [ ] 21. valid_credit_card: 'The %s field must contain a valid credit card number.',
- [ ] 22. is_file_type: 'The %s field must contain only %s files.',
- [ ] 24. greater_than_date: 'The %s field must contain a more recent date than %s.',
- [ ] 25. less_than_date: 'The %s field must contain an older date than %s.',
- [ ] 26. greater_than_or_equal_date: 'The %s field must contain a date that\'s at least as recent as %s.',
- [ ] 27.  less_than_or_equal_date: 'The %s field must contain a date that\'s %s or older.'

**Comment by Qquanwei** [comment]
已经可以发布了
